### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by h5aaimtron** [GamerDude27/MOHAA-Source#1]
Is this an attempt to recreate MOHAA with a different engine? I pulled the code and built it, but didn't see anything of use yet.

**Comment by GamerDude27** [comment]
Hey, sorry for the late reply.

And yes you would be right. I started this project a long time ago when I had some spare time for it. I ended up not committing the latest changes (HUD, weapons, etc.) to this repo, so the current state of this remains a clone of HL2DM.

Maybe I'll get back to it in the future, but for now, it's on hold indefinitely.
